version: '3'
networks:
  dev:
    driver: bridge
services:
  nginx:
    container_name: nginx
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    networks:
      - dev
